#ifndef CLOCK_CONFIG_H
#define CLOCK_CONFIG_H

#define PIN_DISPLAY_DIGIT0 (10)
#define PIN_DISPLAY_DIGIT1 (11)
#define PIN_DISPLAY_DIGIT2 (12)
#define PIN_DISPLAY_DIGIT3 (13)

#define PIN_DISPLAY_SEGMENT_A (22)
#define PIN_DISPLAY_SEGMENT_B (23)
#define PIN_DISPLAY_SEGMENT_C (24)
#define PIN_DISPLAY_SEGMENT_D (25)
#define PIN_DISPLAY_SEGMENT_E (26)
#define PIN_DISPLAY_SEGMENT_F (27)
#define PIN_DISPLAY_SEGMENT_G (28)

#endif /* CLOCK_CONFIG_H */