#ifndef CLOCK_CONFIG_H
#define CLOCK_CONFIG_H

#define DISPLAY_USE_7SEG (1)

#if DISPLAY_USE_7SEG

#define PIN_DISPLAY_DIGIT0 (10)
#define PIN_DISPLAY_DIGIT1 (11)
#define PIN_DISPLAY_DIGIT2 (12)
#define PIN_DISPLAY_DIGIT3 (13)

#define PIN_DISPLAY_SEGMENT_A (22)
#define PIN_DISPLAY_SEGMENT_B (23)
#define PIN_DISPLAY_SEGMENT_C (24)
#define PIN_DISPLAY_SEGMENT_D (25)
#define PIN_DISPLAY_SEGMENT_E (26)
#define PIN_DISPLAY_SEGMENT_F (27)
#define PIN_DISPLAY_SEGMENT_G (28)

#endif /* DISPLAY_USE_7SEG */

#define PIN_BUTTON_0 (30)
#define PIN_BUTTON_1 (31)
#define PIN_BUTTON_2 (32)
#define PIN_BUTTON_3 (33)

#define ACTIONS_MAX_BUTTONS (4)
#define ACTIONS_DOUBLE_CLICK_MAX_MILLISECONDS_SINCE_LAST_RELEASE (250)
#define ACTIONS_LONG_PRESS_MIN_MILLISECONDS (250)

#endif /* CLOCK_CONFIG_H */
